# Generated by Django 5.2.1 on 2025-07-03 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('portrait_url', models.URLField(blank=True, null=True)),
                ('game', models.CharField(default='Ultimate', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tournament_name', models.CharField(blank=True, max_length=255, null=True)),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
                ('attendees', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Colombia Tournament',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('gamertag', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('prefijo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('discord', models.CharField(blank=True, max_length=100, null=True)),
                ('twitch', models.CharField(blank=True, max_length=100, null=True)),
                ('secundary_character', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('main_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Consultas.character')),
            ],
            options={
                'db_table': 'Colombia_Players',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('player_1_score', models.IntegerField()),
                ('player_2_score', models.IntegerField()),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.event')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_as_player_1', to='Consultas.player')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_as_player_2', to='Consultas.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_won', to='Consultas.player')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.tournament'),
        ),
        migrations.CreateModel(
            name='CharacterSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_number', models.IntegerField()),
                ('skin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='Consultas.character')),
            ],
            options={
                'ordering': ['skin_number'],
                'unique_together': {('character', 'skin_number')},
            },
        ),
        migrations.CreateModel(
            name='MatchCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.character')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.player')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.set')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Consultas.tournament')),
            ],
            options={
                'ordering': ['game_number'],
                'unique_together': {('set', 'player', 'game_number')},
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.BigIntegerField()),
                ('gamertag', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultas.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
