# Generated by Django 5.2.1 on 2025-07-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultas', '0001_initial'),
    ]

    operations = [
    ]
